"""Datos de las páginas de envío por ciudad (/pasto-sintetico/envio/<slug>).

Texto propio por ciudad: clima, modelos recomendados y preguntas. No repetir textos entre ciudades.
Los precios se calculan en ciudad.py con data.landed_m2; aquí no se escriben precios.
`estado` usa la misma clave que ESTADO_ZONA en public/js/tienda-pasto.js.
"""

CIUDADES = [
    dict(slug="cdmx", nombre="CDMX", nombre_largo="Ciudad de México", estado="CDMX",
         intro="En la Ciudad de México el pasto sintético se usa mucho en azoteas, terrazas y patios de casas y departamentos, donde el espacio es chico y regar o podar es poco práctico. También se pone en áreas comunes de edificios y en jardines pequeños.",
         clima="En la Ciudad de México llueve fuerte de junio a septiembre y en invierno hay mañanas frías. Conviene un pasto con base perforada que drene rápido y fibra que recupere su forma en azoteas y patios.",
         modelos=[("toscana-28", "El más vendido: aguanta el uso diario de un patio familiar."),
                  ("toscana-18", "Ligero para subir a azoteas y balcones, donde importa el peso."),
                  ("irlanda-25", "Fibra resistente para perros y paso constante en el patio.")],
         faqs=[("¿Pueden enviarlo a una azotea en la Ciudad de México?", "Enviamos el rollo a tu dirección por paquetería. Subirlo a la azotea corre por tu cuenta; un rollo completo pesa varias decenas de kilos, así que conviene que estén dos personas al recibirlo."),
               ("¿Aguanta las lluvias de verano en la CDMX?", "Sí. La base es perforada y drena el agua. Para que no se encharque, instálalo sobre una capa de grava fina compactada o sobre un piso con desnivel."),
               ("¿Cuánto tarda en llegar a la Ciudad de México?", "De 3 a 5 días hábiles después de confirmar el pago, con guía de rastreo.")]),
    dict(slug="guadalajara", nombre="Guadalajara", nombre_largo="Guadalajara, Jalisco", estado="Jalisco",
         intro="En Guadalajara y su zona metropolitana el pasto sintético se coloca en patios traseros, jardines de casas en privadas y áreas junto a la alberca. Es una opción para quien no quiere depender del riego en la temporada de calor.",
         clima="Guadalajara tiene primaveras muy secas y calurosas y un verano de lluvias intensas. El pasto sintético evita regar en la época de escasez de agua y drena bien en temporada de tormentas.",
         modelos=[("toscana-28", "Equilibrio entre precio, volumen y resistencia para el jardín de casa."),
                  ("capri-20", "Alta densidad para patios donde juegan niños todos los días."),
                  ("viena-30", "Más volumen y aspecto natural para jardines que se quieren lucir.")],
         faqs=[("¿Conviene pasto sintético en Guadalajara por el agua?", "Sí. No necesita riego, solo un enjuague ocasional para quitar polvo. En primavera, cuando el pasto natural sufre, el sintético se mantiene verde."),
               ("¿Envían a Zapopan y Tlaquepaque?", "Sí. Enviamos a toda la zona metropolitana de Guadalajara con el flete de Jalisco, que se confirma con tu código postal antes de pagar."),
               ("¿Qué base necesito en Guadalajara?", "Grava fina o polvo de piedra compactado, de 5 a 8 cm, para que drene en la temporada de lluvias.")]),
    dict(slug="queretaro", nombre="Querétaro", nombre_largo="Querétaro", estado="Querétaro",
         intro="En Querétaro el pasto sintético se pone sobre todo en los jardines y patios de casas en fraccionamientos nuevos, donde el terreno llega sin área verde. También se usa en terrazas y en patios de casas con perros.",
         clima="Querétaro es seco la mayor parte del año, con polvo y sol fuerte. El pasto sintético se limpia con una barrida o un enjuague y no se amarilla como el pasto natural en la temporada seca.",
         modelos=[("toscana-18", "Económico y fácil de limpiar para el patio de una casa nueva."),
                  ("toscana-28", "Más volumen para el jardín frontal de un fraccionamiento."),
                  ("irlanda-25", "Fibra resistente si tienes perros que corren en el patio.")],
         faqs=[("¿El polvo de Querétaro ensucia el pasto sintético?", "Se acumula como en cualquier piso exterior. Se quita con escoba de cerdas duras o con un enjuague con manguera."),
               ("¿Sirve para casas nuevas en Querétaro?", "Sí. En casas nuevas el terreno suele ser de relleno: compáctalo y pon una capa de grava fina antes de extender el rollo."),
               ("¿Cuánto tarda en llegar a Querétaro?", "De 3 a 5 días hábiles después de confirmar el pago.")]),
    dict(slug="san-luis-potosi", nombre="San Luis Potosí", nombre_largo="San Luis Potosí", estado="San Luis Potosí",
         intro="En San Luis Potosí el pasto sintético se coloca en patios y jardines de casas, áreas de juego de niños y terrazas. Es una alternativa verde para quien vive en una zona de poca lluvia y prefiere no regar.",
         clima="San Luis Potosí es semiárido: poca lluvia, sol intenso y noches frescas. Un pasto con protección UV conserva su color y no necesita agua.",
         modelos=[("toscana-28", "Buena relación entre precio y volumen para el jardín familiar."),
                  ("toscana-18", "Opción económica para patios chicos y áreas de paso corto."),
                  ("japones-35", "El de mayor altura de fibra, para jardines de lucimiento.")],
         faqs=[("¿Se decolora con el sol de San Luis Potosí?", "Todos los modelos tienen protección UV de fábrica para conservar el color. La garantía de fábrica va de 3 a 8 años según el modelo."),
               ("¿Envían a Soledad de Graciano Sánchez?", "Sí, con el flete de San Luis Potosí, que se confirma con tu código postal antes de pagar."),
               ("¿Lo puedo poner sobre tierra?", "Sobre tierra compactada con una capa de grava fina, sí. Sobre tierra suelta se hunde y se hacen charcos.")]),
    dict(slug="leon", nombre="León", nombre_largo="León, Guanajuato", estado="Guanajuato",
         intro="En León el pasto sintético se usa en patios traseros, jardines frontales de casas en fraccionamientos y terrazas. También lo eligen quienes quieren un área verde para niños o mascotas sin mantener pasto natural.",
         clima="León tiene calor seco en primavera y lluvias en verano. El pasto sintético ahorra agua en los meses secos y drena en temporada de lluvias.",
         modelos=[("toscana-28", "Resistente y con buen volumen para el jardín de casa."),
                  ("capri-20", "Denso para el patio donde los niños juegan seguido."),
                  ("toscana-18", "Económico para terrazas y áreas chicas.")],
         faqs=[("¿Envían a otras ciudades de Guanajuato?", "Sí. Enviamos a todo Guanajuato, incluidos Irapuato, Celaya y Silao, con el flete de Guanajuato, que se confirma con tu código postal antes de pagar."),
               ("¿Es seguro para niños?", "Sí. Todos los modelos tienen tratamiento antibacterial y retardante al fuego de fábrica."),
               ("¿Cuánto tarda en llegar a León?", "De 3 a 5 días hábiles después de confirmar el pago.")]),
    dict(slug="puebla", nombre="Puebla", nombre_largo="Puebla", estado="Puebla",
         intro="En Puebla el pasto sintético se pone con frecuencia en jardines frontales, patios interiores de casas y terrazas de departamento. Se elige para tener un área verde que se vea cuidada todo el año sin podar.",
         clima="Puebla es templada, con lluvias de mayo a octubre y mañanas frías en invierno. Conviene un pasto con base que drene y fibra que se vea natural todo el año.",
         modelos=[("toscana-28", "Buen volumen para el jardín de una casa con patio al frente."),
                  ("viena-30", "Aspecto natural más pulido para el jardín frontal."),
                  ("toscana-18", "Ligero para balcones y terrazas de departamento.")],
         faqs=[("¿Aguanta las heladas de invierno en Puebla?", "Sí. El pasto sintético no se quema con el frío como el pasto natural y conserva su color."),
               ("¿Envían a Cholula y Atlixco?", "Sí, con el flete de Puebla, que se confirma con tu código postal antes de pagar."),
               ("¿Cuánto tarda en llegar a Puebla?", "De 3 a 5 días hábiles después de confirmar el pago.")]),
    dict(slug="monterrey", nombre="Monterrey", nombre_largo="Monterrey, Nuevo León", estado="Nuevo León",
         intro="En Monterrey el pasto sintético se coloca en patios traseros, cocheras abiertas y jardines de casas en colonias residenciales. También se usa en terrazas y áreas de asador, donde la gente busca un piso verde sin mantenimiento de riego.",
         clima="Monterrey tiene veranos de calor extremo y temporadas de restricción de agua. El pasto sintético no se seca ni necesita riego; en pleno sol conviene una fibra densa que recupere su forma.",
         modelos=[("irlanda-25", "Fibra resistente para zonas de sol fuerte y uso diario."),
                  ("toscana-28", "Buen volumen y precio para el patio trasero."),
                  ("bali-35", "Mucha altura de fibra para jardines que se quieren lucir.")],
         faqs=[("¿El pasto sintético se calienta con el sol de Monterrey?", "Sí, como cualquier superficie al sol. Un enjuague con manguera antes de usarlo en las horas de más calor baja su temperatura."),
               ("¿Envían a San Pedro, Apodaca y Santa Catarina?", "Sí. Enviamos a toda la zona metropolitana de Monterrey con el flete de Nuevo León, que se confirma con tu código postal antes de pagar."),
               ("¿Conviene en Monterrey por la falta de agua?", "Sí. No necesita riego ni poda, y se mantiene verde en la temporada seca.")]),
    dict(slug="veracruz", nombre="Veracruz", nombre_largo="Veracruz y Boca del Río", estado="Veracruz",
         intro="En Veracruz y Boca del Río el pasto sintético se usa en patios de casas, terrazas con vista al mar y áreas junto a la alberca. Es una opción para quien quiere un área verde en una zona de clima húmedo.",
         clima="En Veracruz y Boca del Río hay humedad, salitre y nortes. Conviene un pasto con base perforada que drene rápido y una instalación bien fijada en las orillas para que el viento no la levante.",
         modelos=[("toscana-28", "Resistente para jardines de casa en zona de costa."),
                  ("capri-20", "Fibra densa para patios con mucho uso cotidiano."),
                  ("irlanda-25", "Fibra resistente si tienes perros.")],
         faqs=[("¿El salitre daña el pasto sintético?", "No lo pudre como a la madera. Un enjuague con agua dulce de vez en cuando quita la sal acumulada."),
               ("¿Se levanta con los nortes?", "Si las orillas quedan bien fijadas con clavos o adhesivo, no. En la guía de instalación explicamos cómo fijarlas."),
               ("¿Envían a Boca del Río y Xalapa?", "Sí. Enviamos a todo el estado de Veracruz con el flete de Veracruz, que se confirma con tu código postal antes de pagar.")]),
    dict(slug="merida", nombre="Mérida", nombre_largo="Mérida, Yucatán", estado="Yucatán",
         intro="En Mérida el pasto sintético se pone sobre todo en patios de casas con piso de piedra, áreas de alberca y terrazas. Permite tener un área verde sin cargar tierra ni regar.",
         clima="Mérida tiene calor todo el año, suelo de roca caliza y lluvias fuertes en verano. Sobre piedra, el pasto sintético da un jardín verde sin tierra ni riego; la base debe nivelarse con polvo de piedra para que drene.",
         modelos=[("toscana-28", "Equilibrio de precio y volumen para patios y jardines sobre piedra nivelada."),
                  ("irlanda-25", "Fibra resistente para uso diario en clima caluroso."),
                  ("viena-30", "Volumen extra para jardines donde importa la vista.")],
         faqs=[("¿Se puede poner pasto sintético sobre el suelo de piedra de Mérida?", "Sí. Nivela con polvo de piedra o grava fina, compacta y extiende el rollo encima. Es una de las ventajas frente al pasto natural."),
               ("¿Aguanta las lluvias de verano en Mérida?", "Sí. La base perforada drena el agua si la base de grava tiene desnivel hacia una salida de agua."),
               ("¿Cuánto tarda en llegar a Mérida?", "De 3 a 5 días hábiles después de confirmar el pago, según la paquetería.")]),
    dict(slug="cancun", nombre="Cancún", nombre_largo="Cancún, Quintana Roo", estado="Quintana Roo",
         intro="En Cancún el pasto sintético se coloca en terrazas, áreas de alberca y jardines de casas de renta vacacional y condominios. Es una opción práctica para espacios que se usan mucho y se quieren ver verdes sin trabajo de jardinería.",
         clima="Cancún tiene sol intenso, arena, salitre y temporada de huracanes. El pasto sintético con protección UV se mantiene verde junto a albercas y terrazas, y se enjuaga para quitar arena y sal.",
         modelos=[("toscana-28", "Para jardines y áreas junto a la alberca."),
                  ("capri-20", "Denso y resistente para rentas vacacionales con mucho movimiento."),
                  ("toscana-18", "Ligero para terrazas y roof gardens.")],
         faqs=[("¿Sirve alrededor de la alberca?", "Sí. Drena el agua y no se hace lodo. Enjuágalo de vez en cuando para quitar cloro, arena y sal."),
               ("¿Envían a Playa del Carmen y Tulum?", "Sí. Enviamos a todo Quintana Roo con el flete de Quintana Roo, que se confirma con tu código postal antes de pagar; en poblaciones alejadas puede variar."),
               ("¿Qué hago en temporada de huracanes?", "Revisa que las orillas estén bien fijadas. Si el agua arrastra arena o ramas, límpialo con escoba y enjuágalo.")]),
    dict(slug="villahermosa", nombre="Villahermosa", nombre_largo="Villahermosa, Tabasco", estado="Tabasco",
         intro="En Villahermosa el pasto sintético se usa en patios y jardines de casas, áreas de juego de niños y espacios donde el pasto natural cuesta mantener por la humedad. Sirve para tener un área verde con menos cuidados.",
         clima="Villahermosa tiene calor húmedo y lluvias muy intensas buena parte del año. Lo más importante es la base: grava con desnivel para que el agua salga rápido y el pasto no se quede encharcado.",
         modelos=[("toscana-28", "Resistente para jardines que reciben lluvias frecuentes."),
                  ("irlanda-25", "Fibra firme para perros y paso diario en el patio."),
                  ("capri-20", "Alta densidad para patios con mucho paso de personas.")],
         faqs=[("¿Se encharca con las lluvias de Tabasco?", "El pasto drena, pero si el terreno no tiene salida el agua se queda abajo. Por eso la base de grava con desnivel es clave."),
               ("¿Le salen hongos con la humedad?", "Al no tener tierra ni raíces, no le salen hongos como al pasto natural. Si se acumula materia orgánica, enjuágalo y cepíllalo."),
               ("¿Cuánto tarda en llegar a Villahermosa?", "De 3 a 5 días hábiles después de confirmar el pago.")]),
]
