"""Datos de las páginas de envío por ciudad (/pasto-sintetico/envio/<slug>).

Texto propio por ciudad: clima, modelos recomendados y preguntas. No repetir textos entre ciudades.
Los precios se calculan en ciudad.py con data.landed_m2; aquí no se escriben precios.
`estado` usa la misma clave que ESTADO_ZONA en public/js/tienda-pasto.js.
"""

CIUDADES = [
    dict(slug="cdmx", nombre="CDMX", nombre_largo="Ciudad de México", estado="CDMX",
         clima="En la Ciudad de México llueve fuerte de junio a septiembre y en invierno hay mañanas frías. Conviene un pasto con base perforada que drene rápido y fibra que recupere su forma en azoteas y patios.",
         modelos=[("toscana-28", "El más vendido: aguanta el uso diario de patio familiar."),
                  ("toscana-18", "Ligero para azoteas y balcones donde importa el peso."),
                  ("irlanda-25", "Fibra resistente para perros y pisoteo diario.")],
         faqs=[("¿Pueden enviarlo a una azotea en la Ciudad de México?", "Enviamos el rollo a tu dirección por paquetería. Subirlo a la azotea corre por tu cuenta; un rollo completo pesa varias decenas de kilos, así que conviene que estén dos personas al recibirlo."),
               ("¿Aguanta las lluvias de verano en la CDMX?", "Sí. La base es perforada y drena el agua. Para que no se encharque, instálalo sobre una capa de grava fina compactada o sobre un piso con desnivel."),
               ("¿Cuánto tarda en llegar a la Ciudad de México?", "De 3 a 5 días hábiles después de confirmar el pago, con guía de rastreo.")]),
    dict(slug="guadalajara", nombre="Guadalajara", nombre_largo="Guadalajara, Jalisco", estado="Jalisco",
         clima="Guadalajara tiene primaveras muy secas y calurosas y un verano de lluvias intensas. El pasto sintético evita regar en la época de escasez de agua y drena bien en temporada de tormentas.",
         modelos=[("toscana-28", "Equilibrio entre precio, volumen y resistencia para jardín."),
                  ("capri-20", "Alta densidad para patios con mucho uso."),
                  ("viena-30", "Más volumen y aspecto natural para jardines de lucimiento.")],
         faqs=[("¿Conviene pasto sintético en Guadalajara por el agua?", "Sí. No necesita riego, solo un enjuague ocasional para quitar polvo. En primavera, cuando el pasto natural sufre, el sintético se mantiene verde."),
               ("¿Envían a Zapopan y Tlaquepaque?", "Sí. Enviamos a toda la zona metropolitana de Guadalajara con el flete de Jalisco."),
               ("¿Qué base necesito en Guadalajara?", "Grava fina o polvo de piedra compactado, de 5 a 8 cm, para que drene en la temporada de lluvias.")]),
    dict(slug="queretaro", nombre="Querétaro", nombre_largo="Querétaro", estado="Querétaro",
         clima="Querétaro es seco la mayor parte del año, con polvo y sol fuerte. El pasto sintético se limpia con una barrida o un enjuague y no se amarilla en la temporada seca.",
         modelos=[("toscana-18", "Económico y fácil de limpiar para patios de casa nueva."),
                  ("toscana-28", "Más volumen para jardines de fraccionamiento."),
                  ("irlanda-25", "Fibra resistente si tienes perros.")],
         faqs=[("¿El polvo de Querétaro ensucia el pasto sintético?", "Se acumula como en cualquier piso exterior. Se quita con escoba de cerdas duras o con un enjuague con manguera."),
               ("¿Sirve para casas nuevas en Querétaro?", "Sí. En casas nuevas el terreno suele ser de relleno: compáctalo y pon una capa de grava fina antes de extender el rollo."),
               ("¿Cuánto tarda en llegar a Querétaro?", "De 3 a 5 días hábiles después de confirmar el pago.")]),
    dict(slug="san-luis-potosi", nombre="San Luis Potosí", nombre_largo="San Luis Potosí", estado="San Luis Potosí",
         clima="San Luis Potosí es semiárido: poca lluvia, sol intenso y noches frescas. Un pasto con protección UV conserva su color y no necesita agua.",
         modelos=[("toscana-28", "El más vendido para jardín familiar."),
                  ("toscana-18", "Opción económica para patios chicos."),
                  ("japones-35", "Máximo volumen para jardines de lucimiento.")],
         faqs=[("¿Se decolora con el sol de San Luis Potosí?", "Todos los modelos tienen protección UV de fábrica para conservar el color. La garantía de fábrica va de 3 a 8 años según el modelo."),
               ("¿Envían a Soledad de Graciano Sánchez?", "Sí, con el mismo flete de San Luis Potosí."),
               ("¿Lo puedo poner sobre tierra?", "Sobre tierra compactada con una capa de grava fina, sí. Sobre tierra suelta se hunde y se hacen charcos.")]),
    dict(slug="leon", nombre="León", nombre_largo="León, Guanajuato", estado="Guanajuato",
         clima="León tiene calor seco en primavera y lluvias en verano. El pasto sintético ahorra agua en los meses secos y drena en temporada de lluvias.",
         modelos=[("toscana-28", "Resistente y con buen volumen para jardín."),
                  ("capri-20", "Denso para patios de juego de niños."),
                  ("toscana-18", "Económico para terrazas y áreas chicas.")],
         faqs=[("¿Envían a otras ciudades de Guanajuato?", "Sí. Enviamos a todo Guanajuato, incluidos Irapuato, Celaya y Silao, con el flete de la zona."),
               ("¿Es seguro para niños?", "Sí. Todos los modelos tienen tratamiento antibacterial y retardante al fuego de fábrica."),
               ("¿Cuánto tarda en llegar a León?", "De 3 a 5 días hábiles después de confirmar el pago.")]),
    dict(slug="puebla", nombre="Puebla", nombre_largo="Puebla", estado="Puebla",
         clima="Puebla es templada, con lluvias de mayo a octubre y mañanas frías en invierno. Conviene un pasto con base que drene y fibra que se vea natural todo el año.",
         modelos=[("toscana-28", "El más vendido para jardines de casa."),
                  ("viena-30", "Aspecto natural premium para jardín frontal."),
                  ("toscana-18", "Ligero para balcones y terrazas.")],
         faqs=[("¿Aguanta las heladas de invierno en Puebla?", "Sí. El pasto sintético no se quema con el frío como el pasto natural y conserva su color."),
               ("¿Envían a Cholula y Atlixco?", "Sí, con el mismo flete de Puebla."),
               ("¿Cuánto tarda en llegar a Puebla?", "De 3 a 5 días hábiles después de confirmar el pago.")]),
    dict(slug="monterrey", nombre="Monterrey", nombre_largo="Monterrey, Nuevo León", estado="Nuevo León",
         clima="Monterrey tiene veranos de calor extremo y temporadas de restricción de agua. El pasto sintético no se seca ni necesita riego; en pleno sol conviene una fibra densa que recupere su forma.",
         modelos=[("irlanda-25", "Fibra resistente para calor y uso diario."),
                  ("toscana-28", "El más vendido: buen volumen y precio."),
                  ("bali-35", "El más completo para jardines de lucimiento.")],
         faqs=[("¿El pasto sintético se calienta con el sol de Monterrey?", "Sí, como cualquier superficie al sol. Un enjuague con manguera antes de usarlo en las horas de más calor baja su temperatura."),
               ("¿Envían a San Pedro, Apodaca y Santa Catarina?", "Sí. Enviamos a toda la zona metropolitana de Monterrey con el flete de Nuevo León."),
               ("¿Conviene en Monterrey por la falta de agua?", "Sí. No necesita riego ni poda, y se mantiene verde en la temporada seca.")]),
    dict(slug="veracruz", nombre="Veracruz", nombre_largo="Veracruz y Boca del Río", estado="Veracruz",
         clima="En Veracruz y Boca del Río hay humedad, salitre y nortes. Conviene un pasto con base perforada que drene rápido y una instalación bien fijada en las orillas para que el viento no la levante.",
         modelos=[("toscana-28", "Resistente para jardines de casa en la costa."),
                  ("capri-20", "Alta densidad para patios con mucho uso."),
                  ("irlanda-25", "Fibra resistente para perros.")],
         faqs=[("¿El salitre daña el pasto sintético?", "No lo pudre como a la madera. Un enjuague con agua dulce de vez en cuando quita la sal acumulada."),
               ("¿Se levanta con los nortes?", "Si las orillas quedan bien fijadas con clavos o adhesivo, no. En la guía de instalación explicamos cómo fijarlas."),
               ("¿Envían a Boca del Río y Xalapa?", "Sí. Enviamos a todo el estado de Veracruz con el flete de la zona.")]),
    dict(slug="merida", nombre="Mérida", nombre_largo="Mérida, Yucatán", estado="Yucatán",
         clima="Mérida tiene calor todo el año, suelo de roca caliza y lluvias fuertes en verano. Sobre piedra, el pasto sintético da un jardín verde sin tierra ni riego; la base debe nivelarse con polvo de piedra para que drene.",
         modelos=[("toscana-28", "El más vendido para patios y jardines."),
                  ("irlanda-25", "Fibra resistente al uso diario y al calor."),
                  ("viena-30", "Más volumen para jardines de lucimiento.")],
         faqs=[("¿Se puede poner pasto sintético sobre el suelo de piedra de Mérida?", "Sí. Nivela con polvo de piedra o grava fina, compacta y extiende el rollo encima. Es una de las ventajas frente al pasto natural."),
               ("¿Aguanta las lluvias de verano en Mérida?", "Sí. La base perforada drena el agua si la base de grava tiene desnivel hacia una salida."),
               ("¿Cuánto tarda en llegar a Mérida?", "De 3 a 5 días hábiles después de confirmar el pago, según la paquetería.")]),
    dict(slug="cancun", nombre="Cancún", nombre_largo="Cancún, Quintana Roo", estado="Quintana Roo",
         clima="Cancún tiene sol intenso, arena, salitre y temporada de huracanes. El pasto sintético con protección UV se mantiene verde junto a albercas y terrazas, y se enjuaga para quitar arena y sal.",
         modelos=[("toscana-28", "Para jardines y áreas de alberca."),
                  ("capri-20", "Denso y resistente para rentas vacacionales con mucho uso."),
                  ("toscana-18", "Ligero para terrazas y roof gardens.")],
         faqs=[("¿Sirve alrededor de la alberca?", "Sí. Drena el agua y no se hace lodo. Enjuágalo de vez en cuando para quitar cloro, arena y sal."),
               ("¿Envían a Playa del Carmen y Tulum?", "Sí. Enviamos a todo Quintana Roo con el flete de la zona; en poblaciones alejadas el flete puede variar y te lo confirmamos."),
               ("¿Qué hago en temporada de huracanes?", "Revisa que las orillas estén bien fijadas. Si el agua arrastra arena o ramas, límpialo con escoba y enjuágalo.")]),
    dict(slug="villahermosa", nombre="Villahermosa", nombre_largo="Villahermosa, Tabasco", estado="Tabasco",
         clima="Villahermosa tiene calor húmedo y lluvias muy intensas buena parte del año. Lo más importante es la base: grava con desnivel para que el agua salga rápido y el pasto no se quede encharcado.",
         modelos=[("toscana-28", "Resistente para jardines con lluvias frecuentes."),
                  ("irlanda-25", "Fibra resistente para perros y uso diario."),
                  ("capri-20", "Alta densidad para patios con mucho paso.")],
         faqs=[("¿Se encharca con las lluvias de Tabasco?", "El pasto drena, pero si el terreno no tiene salida el agua se queda abajo. Por eso la base de grava con desnivel es clave."),
               ("¿Le salen hongos con la humedad?", "El pasto sintético no genera hongos como el natural. Si se acumula materia orgánica, enjuágalo y cepíllalo."),
               ("¿Cuánto tarda en llegar a Villahermosa?", "De 3 a 5 días hábiles después de confirmar el pago.")]),
]
